SEED_PRODUCTS = [
    {
        "name": "Baldur's Gate 3",
        "description": "RPG tatico baseado em turnos com foco em narrativa, escolhas e combate estrategico em grupo.",
        "price": "229.90",
        "image": "Baldur's-Gate-3.webp",
        "tags": ["rpg", "acao", "fantasia"],
    },
    {
        "name": "Cyberpunk 2077",
        "description": "RPG de acao em mundo aberto ambientado em Night City, com enredo denso e customizacao de personagem.",
        "price": "179.90",
        "image": "Cyberpunk-2077.webp",
        "tags": ["rpg", "acao", "mundo-aberto"],
    },
    {
        "name": "Dragon Age: Origins",
        "description": "RPG classico de fantasia com companheiros marcantes, escolhas narrativas e combate tatico em tempo real com pausa.",
        "price": "59.90",
        "image": "Dragon-Age-Origins.webp",
        "tags": ["rpg", "fantasia", "classico"],
    },
    {
        "name": "Fallout 4",
        "description": "RPG de mundo aberto em um cenario pos-apocaliptico, com foco em exploracao, crafting e combate.",
        "price": "149.90",
        "image": "Fallout-4.webp",
        "tags": ["rpg", "mundo-aberto"],
    },
    {
        "name": "Fallout: New Vegas",
        "description": "RPG classico em primeira pessoa no universo Fallout, com escolhas narrativas e faccoes.",
        "price": "79.90",
        "image": "Fallout-New-Vegas.webp",
        "tags": ["rpg", "acao", "classico"],
    },
    {
        "name": "Final Fantasy VII",
        "description": "RPG japones iconico com narrativa marcante, personagens memoraveis e batalhas em ritmo dinamico.",
        "price": "119.90",
        "image": "Final-Fantasy-VII.webp",
        "tags": ["rpg", "jrpg", "classico"],
    },
    {
        "name": "No Man's Sky",
        "description": "Aventura espacial com exploracao procedural, sobrevivencia, construcao de bases e multiplayer.",
        "price": "199.90",
        "image": "No-Man's-Sky.webp",
        "tags": ["aventura", "mundo-aberto"],
    },
    {
        "name": "Saints Row 2",
        "description": "Jogo de acao em mundo aberto com missoes, veiculos e progressao em estilo sandbox urbano.",
        "price": "69.90",
        "image": "Saints-Row-2.webp",
        "tags": ["acao", "mundo-aberto", "sandbox"],
    },
    {
        "name": "Terraria",
        "description": "Aventura 2D com construcao, combate e exploracao em um mundo gerado proceduralmente.",
        "price": "39.90",
        "image": "Terraria.webp",
        "tags": ["aventura", "sandbox", "acao"],
    },
    {
        "name": "The Elder Scrolls V: Skyrim",
        "description": "RPG de fantasia em mundo aberto com exploracao livre, quests variadas e progressao de habilidades.",
        "price": "89.90",
        "image": "The-Elder-Scrolls-V-Skyrim.webp",
        "tags": ["rpg", "fantasia", "mundo-aberto"],
    },
    {
        "name": "The Witcher 3",
        "description": "RPG de acao com narrativa premiada, contratos de monstros e um vasto mundo aberto para explorar.",
        "price": "139.90",
        "image": "The-Witcher-3.webp",
        "tags": ["rpg", "acao", "mundo-aberto"],
    },
    {
        "name": "Tomb Raider",
        "description": "Acao e aventura com exploracao de tumbas, quebra-cabecas e combate cinematografico.",
        "price": "99.90",
        "image": "Tomb-Raider.webp",
        "tags": ["acao", "aventura"],
    },
]